// <auto-generated />
using System;
using Maasgroep.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maasgroep.Database.Migrations
{
    [DbContext(typeof(MaasgroepContext))]
    [Migration("20231214213955_FolderToAlbum")]
    partial class FolderToAlbum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("approvalSeq", "receiptHistory");

            modelBuilder.HasSequence("billSeq", "orderHistory");

            modelBuilder.HasSequence("costCentreSeq", "receipt");

            modelBuilder.HasSequence("costCentreSeq", "receiptHistory");

            modelBuilder.HasSequence("lineSeq", "orderHistory");

            modelBuilder.HasSequence("memberSeq", "admin");

            modelBuilder.HasSequence("permissionSeq", "admin");

            modelBuilder.HasSequence("photoSeq", "receipt");

            modelBuilder.HasSequence("photoSeq", "receiptHistory");

            modelBuilder.HasSequence("productPriceSeq", "orderHistory");

            modelBuilder.HasSequence("productSeq", "order");

            modelBuilder.HasSequence("productSeq", "orderHistory");

            modelBuilder.HasSequence("receiptSeq", "receipt");

            modelBuilder.HasSequence("receiptSeq", "receiptHistory");

            modelBuilder.HasSequence("stockSeq", "orderHistory");

            modelBuilder.HasSequence("todoSeq", "todo");

            modelBuilder.HasSequence("todoSeq", "todoHistory");

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentAlbumId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentAlbumId", "Name")
                        .IsUnique();

                    b.ToTable("albums", "photoAlbum");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LikedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Likes", "photoAlbum");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UploaderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AlbumLocationId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Photos", "photoAlbum");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.PhotoTag", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("PhotoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PhotoTags", "photoAlbum");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", "photoAlbum");
                });

            modelBuilder.Entity("Maasgroep.Database.Members.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('admin.\"memberSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("member", "admin");
                });

            modelBuilder.Entity("Maasgroep.Database.Members.MemberPermission", b =>
                {
                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.HasKey("MemberId", "PermissionId");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.HasIndex("PermissionId");

                    b.ToTable("memberPermission", "admin");
                });

            modelBuilder.Entity("Maasgroep.Database.Members.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('admin.\"permissionSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permission", "admin");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Bill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Note")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberModifiedId");

                    b.ToTable("bill", "order");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.BillHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"orderHistory\".\"billSeq\"')");

                    b.Property<long>("BillId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Note")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("bill", "orderHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Line", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BillId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.HasIndex("ProductId");

                    b.ToTable("line", "order", t =>
                        {
                            t.HasCheckConstraint("CK_orderLine_quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.LineHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"orderHistory\".\"lineSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<long>("LineId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("line", "orderHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('order.\"productSeq\"')");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.ToTable("product", "order");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.ProductHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"orderHistory\".\"productSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("product", "orderHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.ProductPrice", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.ToTable("productPrice", "order", t =>
                        {
                            t.HasCheckConstraint("CK_orderProductPrice_price", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.ProductPriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"orderHistory\".\"productPriceSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("productPrice", "orderHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Stock", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.ToTable("stock", "order", t =>
                        {
                            t.HasCheckConstraint("CK_order_quantity", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.StockHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"orderHistory\".\"stockSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("stock", "orderHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.CostCentre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('receipt.\"costCentreSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("costCentre", "receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.CostCentreHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"receiptHistory\".\"costCentreSeq\"')");

                    b.Property<long>("CostCentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("costCentre", "receiptHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.PhotoHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"receiptHistory\".\"photoSeq\"')");

                    b.Property<string>("Base64Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<long>("PhotoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("fileExtension")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.ToTable("photo", "receiptHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.Receipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('receipt.\"receiptSeq\"')");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long?>("CostCentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ReceiptStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CostCentreId");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.ToTable("receipt", "receipt", t =>
                        {
                            t.HasCheckConstraint("CK_receipt_amount", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.ReceiptApproval", b =>
                {
                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("ReceiptId");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.ToTable("approval", "receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.ReceiptApprovalHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"receiptHistory\".\"approvalSeq\"')");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("approval", "receiptHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.ReceiptHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"receiptHistory\".\"receiptSeq\"')");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long?>("CostCentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReceiptStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("receipt", "receiptHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.ReceiptPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('receipt.\"photoSeq\"')");

                    b.Property<string>("Base64Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<string>("fileExtension")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberModifiedId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("photo", "receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.ToDoList.ToDo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('todo.\"todoSeq\"')");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MemberCreatedId");

                    b.HasIndex("MemberDeletedId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberModifiedId");

                    b.ToTable("todo", "todo");
                });

            modelBuilder.Entity("Maasgroep.Database.ToDoList.ToDoHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"todoHistory\".\"todoSeq\"')");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<long>("MemberCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberDeletedId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberModifiedId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ToDoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("todo", "todoHistory");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Album", b =>
                {
                    b.HasOne("Maasgroep.Database.Context.team_d.Models.Album", "ParentAlbum")
                        .WithMany("ChildAlbums")
                        .HasForeignKey("ParentAlbumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentAlbum");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Like", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maasgroep.Database.Context.team_d.Models.Photo", "Photo")
                        .WithMany("Likes")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Photo", b =>
                {
                    b.HasOne("Maasgroep.Database.Context.team_d.Models.Album", "AlbumLocation")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maasgroep.Database.Members.Member", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumLocation");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.PhotoTag", b =>
                {
                    b.HasOne("Maasgroep.Database.Context.team_d.Models.Photo", "Photo")
                        .WithMany("PhotoTags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maasgroep.Database.Context.team_d.Models.Tag", "Tag")
                        .WithMany("PhotoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Maasgroep.Database.Members.Member", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("MembersCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_member_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("MembersDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_member_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("MembersModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_member_memberModified");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Members.MemberPermission", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("MemberPermissionsCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_memberPermission_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("MemberPermissionsDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_memberPermission_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "Member")
                        .WithMany("Permissions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_memberPermission_member");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("MemberPermissionsModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_memberPermission_memberModified");

                    b.HasOne("Maasgroep.Database.Members.Permission", "Permission")
                        .WithMany("Members")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_memberPermission_permission");

                    b.Navigation("Member");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Maasgroep.Database.Members.Permission", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("PermissionsCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_permission_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("PermissionsDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_permission_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("PermissionsModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_permission_memberModified");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Bill", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("BillsCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderBill_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("BillsDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderBill_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "Member")
                        .WithMany("BillsOwned")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderBill_memberOwned");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("BillsModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderBill_memberModified");

                    b.Navigation("Member");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Line", b =>
                {
                    b.HasOne("Maasgroep.Database.Orders.Bill", "Bill")
                        .WithMany("Lines")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderLine_bill");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("LinesCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderLine_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("LinesDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderLine_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("LinesModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderLine_memberModified");

                    b.HasOne("Maasgroep.Database.Orders.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderLine_product");

                    b.Navigation("Bill");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Product", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("ProductsCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderProduct_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("ProductsDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderProduct_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("ProductsModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderProduct_memberModified");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.ProductPrice", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("ProductPricesCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderProductPrice_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("ProductPricesDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderProductPrice_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("ProductPricesModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderProductPrice_memberModified");

                    b.HasOne("Maasgroep.Database.Orders.Product", "Product")
                        .WithOne("ProductPrice")
                        .HasForeignKey("Maasgroep.Database.Orders.ProductPrice", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderProductPrice_product");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Stock", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("StocksCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderStock_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("StocksDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderStock_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("StocksModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_orderStock_memberModified");

                    b.HasOne("Maasgroep.Database.Orders.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("Maasgroep.Database.Orders.Stock", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orderStock_product");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.CostCentre", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("CostCentresCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_costCentre_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("CostCentresDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_costCentre_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("CostCentresModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_costCentre_memberModified");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.Receipt", b =>
                {
                    b.HasOne("Maasgroep.Database.Receipts.CostCentre", "CostCentre")
                        .WithMany("Receipt")
                        .HasForeignKey("CostCentreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receipt_costCentre");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("ReceiptsCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_receipt_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("ReceiptsDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receipt_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("ReceiptsModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receipt_memberModified");

                    b.Navigation("CostCentre");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.ReceiptApproval", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("ReceiptApprovalsCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_receiptApproval_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("ReceiptApprovalsDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receiptApproval_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("ReceiptApprovalsModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receiptApproval_memberModified");

                    b.HasOne("Maasgroep.Database.Receipts.Receipt", "Receipt")
                        .WithOne("ReceiptApproval")
                        .HasForeignKey("Maasgroep.Database.Receipts.ReceiptApproval", "ReceiptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_receiptApproval_receipt");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.ReceiptPhoto", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("PhotosCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_photo_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("PhotosDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_photo_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("PhotosModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_photo_memberModified");

                    b.HasOne("Maasgroep.Database.Receipts.Receipt", "Receipt")
                        .WithMany("Photos")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_photo_receipt");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.ToDoList.ToDo", b =>
                {
                    b.HasOne("Maasgroep.Database.Members.Member", "MemberCreated")
                        .WithMany("ToDoCreated")
                        .HasForeignKey("MemberCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_todo_memberCreated");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberDeleted")
                        .WithMany("ToDoDeleted")
                        .HasForeignKey("MemberDeletedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_todo_memberDeleted");

                    b.HasOne("Maasgroep.Database.Members.Member", "Member")
                        .WithMany("ToDoOwned")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_todo_memberOwned");

                    b.HasOne("Maasgroep.Database.Members.Member", "MemberModified")
                        .WithMany("ToDoModified")
                        .HasForeignKey("MemberModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_todo_memberModified");

                    b.Navigation("Member");

                    b.Navigation("MemberCreated");

                    b.Navigation("MemberDeleted");

                    b.Navigation("MemberModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Album", b =>
                {
                    b.Navigation("ChildAlbums");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Photo", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("Maasgroep.Database.Context.team_d.Models.Tag", b =>
                {
                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("Maasgroep.Database.Members.Member", b =>
                {
                    b.Navigation("BillsCreated");

                    b.Navigation("BillsDeleted");

                    b.Navigation("BillsModified");

                    b.Navigation("BillsOwned");

                    b.Navigation("CostCentresCreated");

                    b.Navigation("CostCentresDeleted");

                    b.Navigation("CostCentresModified");

                    b.Navigation("LinesCreated");

                    b.Navigation("LinesDeleted");

                    b.Navigation("LinesModified");

                    b.Navigation("MemberPermissionsCreated");

                    b.Navigation("MemberPermissionsDeleted");

                    b.Navigation("MemberPermissionsModified");

                    b.Navigation("MembersCreated");

                    b.Navigation("MembersDeleted");

                    b.Navigation("MembersModified");

                    b.Navigation("Permissions");

                    b.Navigation("PermissionsCreated");

                    b.Navigation("PermissionsDeleted");

                    b.Navigation("PermissionsModified");

                    b.Navigation("PhotosCreated");

                    b.Navigation("PhotosDeleted");

                    b.Navigation("PhotosModified");

                    b.Navigation("ProductPricesCreated");

                    b.Navigation("ProductPricesDeleted");

                    b.Navigation("ProductPricesModified");

                    b.Navigation("ProductsCreated");

                    b.Navigation("ProductsDeleted");

                    b.Navigation("ProductsModified");

                    b.Navigation("ReceiptApprovalsCreated");

                    b.Navigation("ReceiptApprovalsDeleted");

                    b.Navigation("ReceiptApprovalsModified");

                    b.Navigation("ReceiptsCreated");

                    b.Navigation("ReceiptsDeleted");

                    b.Navigation("ReceiptsModified");

                    b.Navigation("StocksCreated");

                    b.Navigation("StocksDeleted");

                    b.Navigation("StocksModified");

                    b.Navigation("ToDoCreated");

                    b.Navigation("ToDoDeleted");

                    b.Navigation("ToDoModified");

                    b.Navigation("ToDoOwned");
                });

            modelBuilder.Entity("Maasgroep.Database.Members.Permission", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Bill", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Maasgroep.Database.Orders.Product", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("ProductPrice")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.CostCentre", b =>
                {
                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipts.Receipt", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("ReceiptApproval");
                });
#pragma warning restore 612, 618
        }
    }
}
