// <auto-generated />
using System;
using Maasgroep.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ms18_database.Migrations
{
    [DbContext(typeof(MaasgroepContext))]
    partial class MaasgroepContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("costCentreSeq", "receipt");

            modelBuilder.HasSequence("memberSeq", "admin");

            modelBuilder.HasSequence("PhotoSeq", "photo");

            modelBuilder.HasSequence("receiptSeq", "receipt");

            modelBuilder.HasSequence("receiptStatusSeq", "receipt");

            modelBuilder.HasSequence("storeSeq", "receipt");

            modelBuilder.Entity("Maasgroep.Database.CostCentre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('receipt.\"costCentreSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<long>("UserCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserModifiedId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserModifiedId");

                    b.ToTable("costCentre", "receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.MaasgroepMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('admin.\"memberSeq\"')");

                    b.Property<DateTime?>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<long?>("UserCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserModifiedId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserModifiedId");

                    b.ToTable("member", "admin");
                });

            modelBuilder.Entity("Maasgroep.Database.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('photo.\"PhotoSeq\"')");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<long?>("Receipt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Receipt")
                        .IsUnique();

                    b.ToTable("photo", "photo");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('receipt.\"receiptSeq\"')");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("CostCentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(2048)");

                    b.Property<long>("ReceiptStatusId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserModifiedId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CostCentreId");

                    b.HasIndex("ReceiptStatusId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserModifiedId");

                    b.ToTable("receipt", "receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.ReceiptApproval", b =>
                {
                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("varchar(2048)");

                    b.Property<long>("UserCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserModifiedId")
                        .HasColumnType("bigint");

                    b.HasKey("ReceiptId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserModifiedId");

                    b.ToTable("approval", "receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.ReceiptStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('receipt.\"receiptStatusSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<long>("UserCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserModifiedId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserModifiedId");

                    b.ToTable("status", "receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('receipt.\"storeSeq\"')");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<long>("UserCreatedId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserModifiedId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserModifiedId");

                    b.ToTable("store", "receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.CostCentre", b =>
                {
                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserCreated")
                        .WithMany("CostCentresCreated")
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_costCentre_memberCreated");

                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserModified")
                        .WithMany("CostCentresModified")
                        .HasForeignKey("UserModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_costCentre_memberModified");

                    b.Navigation("UserCreated");

                    b.Navigation("UserModified");
                });

            modelBuilder.Entity("Maasgroep.Database.MaasgroepMember", b =>
                {
                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserCreated")
                        .WithMany("MembersCreated")
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_member_memberCreated");

                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserModified")
                        .WithMany("MembersModified")
                        .HasForeignKey("UserModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_member_memberModified");

                    b.Navigation("UserCreated");

                    b.Navigation("UserModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Photo", b =>
                {
                    b.HasOne("Maasgroep.Database.Receipt", "ReceiptInstance")
                        .WithOne("Photo")
                        .HasForeignKey("Maasgroep.Database.Photo", "Receipt")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Photo_Receipt");

                    b.Navigation("ReceiptInstance");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipt", b =>
                {
                    b.HasOne("Maasgroep.Database.CostCentre", "CostCentre")
                        .WithMany("Receipt")
                        .HasForeignKey("CostCentreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receipt_costCentre");

                    b.HasOne("Maasgroep.Database.ReceiptStatus", "ReceiptStatus")
                        .WithMany("Receipt")
                        .HasForeignKey("ReceiptStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_receipt_receiptStatus");

                    b.HasOne("Maasgroep.Database.Store", "Store")
                        .WithMany("Receipt")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receipt_store");

                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserCreated")
                        .WithMany("ReceiptsCreated")
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_receipt_memberCreated");

                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserModified")
                        .WithMany("ReceiptsModified")
                        .HasForeignKey("UserModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receipt_memberModified");

                    b.Navigation("CostCentre");

                    b.Navigation("ReceiptStatus");

                    b.Navigation("Store");

                    b.Navigation("UserCreated");

                    b.Navigation("UserModified");
                });

            modelBuilder.Entity("Maasgroep.Database.ReceiptApproval", b =>
                {
                    b.HasOne("Maasgroep.Database.Receipt", "Receipt")
                        .WithOne("ReceiptApproval")
                        .HasForeignKey("Maasgroep.Database.ReceiptApproval", "ReceiptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_receiptApproval_receipt");

                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserCreated")
                        .WithMany("ReceiptApprovalsCreated")
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_receiptApproval_memberCreated");

                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserModified")
                        .WithMany("ReceiptApprovalsModified")
                        .HasForeignKey("UserModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receiptApproval_memberModified");

                    b.Navigation("Receipt");

                    b.Navigation("UserCreated");

                    b.Navigation("UserModified");
                });

            modelBuilder.Entity("Maasgroep.Database.ReceiptStatus", b =>
                {
                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserCreated")
                        .WithMany("ReceiptStatusesCreated")
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_receiptStatus_memberCreated");

                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserModified")
                        .WithMany("ReceiptStatusesModified")
                        .HasForeignKey("UserModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_receiptStatus_memberModified");

                    b.Navigation("UserCreated");

                    b.Navigation("UserModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Store", b =>
                {
                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserCreated")
                        .WithMany("StoresCreated")
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_store_memberCreated");

                    b.HasOne("Maasgroep.Database.MaasgroepMember", "UserModified")
                        .WithMany("StoresModified")
                        .HasForeignKey("UserModifiedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_store_memberModified");

                    b.Navigation("UserCreated");

                    b.Navigation("UserModified");
                });

            modelBuilder.Entity("Maasgroep.Database.CostCentre", b =>
                {
                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.MaasgroepMember", b =>
                {
                    b.Navigation("CostCentresCreated");

                    b.Navigation("CostCentresModified");

                    b.Navigation("MembersCreated");

                    b.Navigation("MembersModified");

                    b.Navigation("ReceiptApprovalsCreated");

                    b.Navigation("ReceiptApprovalsModified");

                    b.Navigation("ReceiptStatusesCreated");

                    b.Navigation("ReceiptStatusesModified");

                    b.Navigation("ReceiptsCreated");

                    b.Navigation("ReceiptsModified");

                    b.Navigation("StoresCreated");

                    b.Navigation("StoresModified");
                });

            modelBuilder.Entity("Maasgroep.Database.Receipt", b =>
                {
                    b.Navigation("Photo");

                    b.Navigation("ReceiptApproval");
                });

            modelBuilder.Entity("Maasgroep.Database.ReceiptStatus", b =>
                {
                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Maasgroep.Database.Store", b =>
                {
                    b.Navigation("Receipt");
                });
#pragma warning restore 612, 618
        }
    }
}
